channels:
  - conda-forge
  - anaconda
dependencies:
  - datasets
  - pytorch
  - sentence-transformers
  - pip:
    - beir
    - elasticstore>=1.0.3
    - flowfish
    - pacmap==0.6.3
    - vectorspace>=1.0.12