version: '3.3'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global

  portainer:
    # Portainer Community Edition
    # image: portainer/portainer-ce
    # Portainer Business Edition (the first 5 nodes are free)
    image: portainer/portainer-ee
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - agent-network
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager
          - node.labels.portainer.portainer-data == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)
        - traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer
        - traefik.http.routers.portainer.middlewares=portainer-stripprefix
        - traefik.http.routers.portainer.entrypoints=https
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.tls.certresolver=le
        #- traefik.http.routers.portainer.middlewares=admin-auth
        - traefik.http.services.portainer.loadbalancer.server.port=9000
networks:
  agent-network:
    attachable: true
  public:
    external: true

volumes:
  portainer-data:
    labels:
      - node.labels.portainer.portainer-data=true