version: "3.8"

services:
  traefik:
    image: traefik:v2.8.5
    command:
      #- --log.level=DEBUG
      #- --accesslog
      - --api.dashboard=true
      - --providers.docker=true
      # run in swarmmode to expose tasks from all nodes
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.https.address=:443
      - --entrypoints.http.address=:80
      # letsencrypt certificates
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public
    deploy:
      placement:
        constraints:
          # in swarmmode traefik must run on manager
          - node.role==manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        # - traefik.http.middlewares.admin-auth.basicauth.users=${ADMIN_AUTH?Variable not set}
        - traefik.http.middlewares.tf-stripprefix.stripprefix.prefixes=/traefik
        # http redirect
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.tls.certresolver=le
        - traefik.http.routers.traefik.rule=PathPrefix(`/traefik`) || PathPrefix(`/api`)
        - traefik.http.routers.traefik.middlewares=tf-stripprefix #,admin-auth
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik-http.rule=PathPrefix(`/traefik`) || PathPrefix(`/api`)
        - traefik.http.routers.traefik-http.entrypoints=http
        - traefik.http.routers.traefik-http.middlewares=https-redirect
        - traefik.http.services.api.loadbalancer.server.port=8080
networks:
  public:
    external: true
volumes:
  letsencrypt: